spring.application.name=api-gateway
server.port=9000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
spring.main.allow-bean-definition-overriding=true
spring.config.import=optional:configserver:http://localhost:8888

# Routes vers abonnement-service
spring.cloud.gateway.routes[0].id=abonnement-service
spring.cloud.gateway.routes[0].uri=lb://abonnement-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/subscriptions/**,/plans/**,/payments/**,/payment-methods/**

# Discovery locator dynamique
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Frontend CORS support
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowCredentials=true

management.endpoints.web.exposure.include=*
