spring.application.name=abonnement-service
server.port=8086

# Datasource
spring.datasource.url=jdbc:mysql://mysql:3306/abonnementdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=abonnement
spring.datasource.password=abonnement

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stripe
stripe.api.secret-key=${STRIPE_API_SECRET_KEY:}
stripe.api.public-key=${STRIPE_API_PUBLIC_KEY:}

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
spring.main.allow-bean-definition-overriding=true

# Config Server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Actuator
management.endpoints.web.exposure.include=*

welcome.message=Welcome to Abonnement MS
